version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/python'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'pip'
    directory: '/python'
    schedule:
      interval: 'monthly'
