name: reproducible-build
on: [push, pull_request]
jobs:
  build-local:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
        shell: bash
      - name: make
        run: make ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: local-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        index: [0, 1]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build/Run Docker code
        run: make docker ARGS=${{ env.ARGS }}
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}-${{ matrix.index }}
          path: ./ms.pdf
  compare:
    needs: [build-local, build-docker]
    runs-on: ubuntu-20.04
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Compare pdf binaries
        run: |
          diff --from-file
          local-ubuntu-20.04-0/ms.pdf
          docker-ubuntu-20.04-0/ms.pdf
          docker-ubuntu-18.04-0/ms.pdf
          docker-ubuntu-16.04-0/ms.pdf
          local-ubuntu-20.04-1/ms.pdf
          docker-ubuntu-20.04-1/ms.pdf
          docker-ubuntu-18.04-1/ms.pdf
          docker-ubuntu-16.04-1/ms.pdf
      - name: Create file with sha256sum name
        run: echo ::set-env name=sha256sumfilename::$(sha256sum local-ubuntu-20.04-0/ms.pdf | cut -d ' ' -f1)
      - name: Upload file with sha256sum name
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.sha256sumfilename }}
          path: .
